Homework 10
Otus-DevOps-2017-11/frodox_infra pull request #6
Opened 2018-02-07 22:38 UTC by Frodox

В уроке создана база для дальнейшей реализации подхода IaC.

P.s. PR будет заребейзен на `master`, после вливания #5 (чтобы не спутывать diff).

2018-02-08 10:51 UTC, Nklya requested changes
Как-то в диффе не наблюдается ни директории ansible, ни прочего, что добавляется в этом ДЗ.

2018-02-08 19:32 UTC, Frodox commented
@Nklya ну да, `git add .` то я и забыл :D

2018-02-09 10:15 UTC, Nklya approved these changes
Добрый день.

Виталий, условия дз выполнены, теперь все выглядит ок 👍

2018-02-09 10:15 UTC, Nklya commented on terraform/modules/db/output.tf
> +output "db_external_ip" {
Как-то мало смысла от задания только одного output в модуле.

2018-02-09 15:41 UTC, Frodox commented on terraform/modules/db/output.tf
> +output "db_external_ip" {
Хм. А как предполагалось? Я чего-то не уловил, видимо. Можно научить terraform генерить нужный мне inventory, или Вы про задание со звёздочкой, чтобы скрипт спрашивал у terrafrom текие значения и генерил json-inventory? :)

2018-02-09 16:12 UTC, Nklya commented on terraform/modules/db/output.tf
> +output "db_external_ip" {
Не, там было про то, чтобы после terraform apply он выводил еще и ip db инстанса.

2018-02-10 15:26 UTC, Frodox commented on terraform/modules/db/output.tf
> +output "db_external_ip" {
Точно! После разбиения на модули стало сложнее следить что к чему) исправил

2018-02-10 15:26 UTC, merged